openapi: 3.0.0
info:
  title: Jaipur
  version: '1.0'
  description: API pour le jeu de société Jaipur
  contact:
    name: Julien Usson
    email: julien@usson.me
    url: 'https://cours.usson.me'
servers:
  - url: 'http://localhost:3000'
    description: Local
tags:
  - name: Game
    description: Everything about game
  - name: Health
    description: Everything about process health
paths:
  /games:
    post:
      summary: Créer une partie
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/game.yaml
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/create-game.yaml
      operationId: createGame
      tags:
        - Game
    parameters: []
    get:
      summary: Récupérer toutes les parties
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/game.yaml
      description: ''
      parameters: []
      tags:
        - Game
      operationId: findAllGames
  '/games/{id}':
    get:
      summary: Récupérer une partie
      description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/game.yaml
        '404':
          description: Game not found.
      operationId: findOneGameById
      tags:
        - Game
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        description: Identifiant de la partie
    delete:
      summary: Supprimer une partie
      operationId: deleteGameById
      responses:
        '200':
          description: OK
      tags:
        - Game
  /health:
    get:
      summary: Récupérer le status de l'application
      tags:
        - Health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/healthstatus.yaml
      description: ''
      operationId: getHealth
  '/games/{id}/take-good':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        description: Identifiant de la partie
    put:
      summary: Prendre 1 seule marchandise
      operationId: takeGood
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/game.yaml
      parameters:
        - schema:
            type: number
          in: header
          name: playerIndex
          required: true
          description: Index du joueur
      tags:
        - Game
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/take-good-payload.yaml
  '/games/{id}/exchange':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        description: Identifiant de la partie
    put:
      summary: Prendre plusieurs marchandises
      operationId: exchange
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/game.yaml
      parameters:
        - schema:
            type: number
          in: header
          name: playerIndex
          required: true
          description: Index du joueur
      tags:
        - Game
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/exchange-payload.yaml
  '/games/{id}/take-camels':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        description: Identifiant de la partie
    put:
      summary: Prendre les chameaux
      operationId: takeCamels
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/game.yaml
      parameters:
        - schema:
            type: number
          in: header
          name: playerIndex
          required: true
          description: Index du joueur
      tags:
        - Game
  '/games/{id}/sell':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        description: Identifiant de la partie
    put:
      summary: Vendre des cartes
      operationId: sell
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/game.yaml
      parameters:
        - schema:
            type: number
          in: header
          name: playerIndex
          required: true
          description: Index du joueur
      tags:
        - Game
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/sell-payload.yaml
components:
  schemas: {}
