openapi: 3.0.0
info:
  title: Jaipur
  version: '1.0'
  description: API pour le jeu de société Jaipur
  contact:
    name: Julien Usson
    email: julien@usson.me
    url: 'https://cours.usson.me'
servers:
  - url: 'http://localhost:3000'
    description: Local
tags:
  - name: Game
    description: Everything about game
  - name: Health
    description: Everything about process health
paths:
  /games:
    post:
      summary: Create a game
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./models/game.yaml
      description: Créer et initialiser une partie.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/create-game.yaml
      operationId: createGame
      tags:
        - Game
    parameters: []
    get:
      summary: Get all games
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/game.yaml
      description: Lister toutes les parties.
      parameters: []
      tags:
        - Game
      operationId: findAllGames
  '/games/{id}':
    get:
      summary: Get a game
      description: Récupérer une partie via un identifiant.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/game.yaml
        '404':
          description: Game not found.
      operationId: findOneGameById
      tags:
        - Game
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    delete:
      summary: ''
      operationId: deleteGameById
      responses:
        '200':
          description: OK
      tags:
        - Game
  /health:
    get:
      summary: Get application status
      tags:
        - Health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/healthstatus.yaml
      description: Récupérer le status de l'application.
      operationId: getHealth
  '/games/{id}/take-good':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      summary: ''
      operationId: takeGood
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/game.yaml
      parameters:
        - schema:
            type: number
          in: header
          name: playerIndex
          required: true
      tags:
        - Game
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/take-good-payload.yaml
  '/games/{id}/exchange':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      summary: ''
      operationId: exchange
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/game.yaml
      parameters:
        - schema:
            type: number
          in: header
          name: playerIndex
          required: true
      tags:
        - Game
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/exchange-payload.yaml
  '/games/{id}/take-camels':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      summary: ''
      operationId: takeCamels
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/game.yaml
      parameters:
        - schema:
            type: number
          in: header
          name: playerIndex
          required: true
      tags:
        - Game
  '/games/{id}/sell':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      summary: ''
      operationId: sell
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/game.yaml
      parameters:
        - schema:
            type: number
          in: header
          name: playerIndex
          required: true
      tags:
        - Game
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/sell-payload.yaml
components:
  schemas: {}
